AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.7.5
  DisplayCopNames: true
  Include:
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
    - '**/Gemfile'

Layout/LineLength:
  Max: 160

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

Metrics/MethodLength:
  Max: 15
